org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

javaVersion=25

mapstructVersion=1.6.3
springdocVersion=3.0.2
testcontainersVersion=1.20.4
lombokVersion=1.18.38
springCloudVersion=2025.1.0
