CREATE TABLE tenant_settings (
    tenant_id uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
    organization_name text,
    billing_email text,
    support_email text,
    phone text,
    website_url text,
    address_line1 text,
    city text,
    province_code text,
    postal_code text,
    country_code text,
    invoice_prefix text NOT NULL DEFAULT 'INV',
    invoice_footer text,
    payment_terms text,
    logo_url text,
    theme_primary_color text NOT NULL DEFAULT '#0f766e',
    theme_accent_color text NOT NULL DEFAULT '#2563eb',
    email_provider text NOT NULL DEFAULT 'SYSTEM',
    email_sender_name text,
    email_from_address text,
    email_reply_to_address text,
    smtp_host text,
    smtp_port integer,
    smtp_username text,
    smtp_password text,
    smtp_use_tls boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT ck_tenant_settings_email_provider CHECK (email_provider IN ('SYSTEM', 'TENANT_SMTP'))
);

CREATE INDEX idx_tenant_settings_email_provider ON tenant_settings (email_provider);
