#flyway.url=jdbc:postgresql://db.vvfxovvxyswnaaivnqes.supabase.co:5432/postgres
#flyway.user=postgres

flyway.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres
flyway.user=postgres.vvfxovvxyswnaaivnqes
flyway.password=Bull2026shit
flyway.schemas=public
flyway.defaultSchema=public
flyway.locations=filesystem:src/main/resources/db/migration/postgresql
flyway.validateOnMigrate=true
flyway.cleanDisabled=true


