package com.lorne.platform.tenant;

public record TenantPublicSettingsDto(
        String tenantName,
        String legalName,
        String timezone,
        String countryCode,
        String organizationName,
        String billingEmail,
        String supportEmail,
        String phone,
        String websiteUrl,
        String addressLine1,
        String city,
        String provinceCode,
        String postalCode,
        String invoicePrefix,
        String invoiceFooter,
        String paymentTerms,
        String logoUrl,
        String themePrimaryColor,
        String themeAccentColor,
        String emailProvider,
        String emailSenderName,
        String emailFromAddress,
        String emailReplyToAddress,
        String smtpHost,
        Integer smtpPort,
        String smtpUsername,
        boolean smtpPasswordConfigured,
        boolean smtpUseTls,
        boolean liveWorkerTrackingEnabled
) {
    public static TenantPublicSettingsDto from(TenantSettingsView settings) {
        return new TenantPublicSettingsDto(
                settings.tenantName(),
                settings.legalName(),
                settings.timezone(),
                settings.countryCode(),
                settings.organizationName(),
                settings.billingEmail(),
                settings.supportEmail(),
                settings.phone(),
                settings.websiteUrl(),
                settings.addressLine1(),
                settings.city(),
                settings.provinceCode(),
                settings.postalCode(),
                settings.invoicePrefix(),
                settings.invoiceFooter(),
                settings.paymentTerms(),
                settings.logoUrl(),
                settings.themePrimaryColor(),
                settings.themeAccentColor(),
                settings.emailProvider(),
                settings.emailSenderName(),
                settings.emailFromAddress(),
                settings.emailReplyToAddress(),
                settings.smtpHost(),
                settings.smtpPort(),
                settings.smtpUsername(),
                settings.smtpPasswordConfigured(),
                settings.smtpUseTls(),
                settings.liveWorkerTrackingEnabled()
        );
    }
}
