package com.lorne.platform.tenant;

public record TenantPublicSettingsDto(
        String tenantName,
        String legalName,
        String timezone,
        String countryCode,
        String portalSubdomain,
        String organizationName,
        String billingEmail,
        String supportEmail,
        String phone,
        String websiteUrl,
        String addressLine1,
        String addressLine2,
        String city,
        String provinceCode,
        String postalCode,
        String invoicePrefix,
        String invoiceFooter,
        String paymentTerms,
        String logoUrl,
        boolean dayTicketShowCompanyName,
        boolean dayTicketShowCompanyAddress,
        boolean dayTicketShowDailyLoadout,
        boolean serviceRecordShowCompanyName,
        boolean serviceRecordShowCompanyAddress,
        boolean invoiceShowCompanyName,
        boolean invoiceShowCompanyAddress,
        String themePrimaryColor,
        String themeAccentColor,
        String themeNavigationColor,
        String themeSurfaceColor,
        String themePageBackgroundColor,
        String themeDensity,
        String themeRadius,
        java.util.List<String> dashboardWidgetOrder,
        java.util.List<String> dashboardHiddenWidgets,
        String loginStyle,
        String loginHeadline,
        String loginMessage,
        String loginBackgroundPattern,
        boolean loginShowPreview,
        String emailProvider,
        String emailSenderName,
        String emailFromAddress,
        String emailReplyToAddress,
        String smtpHost,
        Integer smtpPort,
        String smtpUsername,
        boolean smtpPasswordConfigured,
        boolean smtpUseTls,
        boolean liveWorkerTrackingEnabled
) {
    public static TenantPublicSettingsDto from(TenantSettingsView settings) {
        return new TenantPublicSettingsDto(
                settings.tenantName(),
                settings.legalName(),
                settings.timezone(),
                settings.countryCode(),
                settings.portalSubdomain(),
                settings.organizationName(),
                settings.billingEmail(),
                settings.supportEmail(),
                settings.phone(),
                settings.websiteUrl(),
                settings.addressLine1(),
                settings.addressLine2(),
                settings.city(),
                settings.provinceCode(),
                settings.postalCode(),
                settings.invoicePrefix(),
                settings.invoiceFooter(),
                settings.paymentTerms(),
                settings.logoUrl(),
                settings.dayTicketShowCompanyName(),
                settings.dayTicketShowCompanyAddress(),
                settings.dayTicketShowDailyLoadout(),
                settings.serviceRecordShowCompanyName(),
                settings.serviceRecordShowCompanyAddress(),
                settings.invoiceShowCompanyName(),
                settings.invoiceShowCompanyAddress(),
                settings.themePrimaryColor(),
                settings.themeAccentColor(),
                settings.themeNavigationColor(),
                settings.themeSurfaceColor(),
                settings.themePageBackgroundColor(),
                settings.themeDensity(),
                settings.themeRadius(),
                settings.dashboardWidgetOrder(),
                settings.dashboardHiddenWidgets(),
                settings.loginStyle(),
                settings.loginHeadline(),
                settings.loginMessage(),
                settings.loginBackgroundPattern(),
                settings.loginShowPreview(),
                settings.emailProvider(),
                settings.emailSenderName(),
                settings.emailFromAddress(),
                settings.emailReplyToAddress(),
                settings.smtpHost(),
                settings.smtpPort(),
                settings.smtpUsername(),
                settings.smtpPasswordConfigured(),
                settings.smtpUseTls(),
                settings.liveWorkerTrackingEnabled()
        );
    }
}
